GET http://localhost:3000/

###
GET http://localhost:3000/app/users

###
GET http://localhost:3000/app/users/cmd4pfokx0000400wxdfwqfxw

###

POST http://localhost:3000/app/register/
Content-Type: application/json

{
  "name": "Diego",
  "lastName": "Souza"
}


###
GET http://localhost:3000/user-auth/users



###
POST http://localhost:3000/user-auth/create-user
Content-Type: application/json

{
  "userId": "cmd4yeqlq00003u0w5oq1kzrb",
  "username": "diego",
  "password": "123456",
  "email": "diegoaguia31@gmail.com"
}