GET http://localhost:3000/

###
GET http://localhost:3000/app/users

###
GET http://localhost:3000/app/users/cmd4pfokx0000400wxdfwqfxw

###

POST http://localhost:3000/app/register/
Content-Type: application/json

{
  "name": "Diego",
  "lastName": "Souza"
}


###
GET http://localhost:3000/user-auth/users



###
POST http://localhost:3000/user-auth/create-user
Content-Type: application/json

{
  "userId": "cmd4yeqlq00003u0w5oq1kzrb",
  "username": "diego",
  "password": "123456",
  "email": "diegoaguia31@gmail.com"
}


###
POST http://localhost:3000/track/create-track
Content-Type: application/json

{
  "name": "Track Name",
  "duration": 300,
  "artistId": "cmd4pfokx0000400wxdfwqfxw",
  "albumId": "cmd4pfokx0000400wxdfwqfxw",
  "genreId": "cmd4pfokx0000400wxdfwqfxw"
}


###
GET http://localhost:3000/genre/all-genres


### 
POST http://localhost:3000/genre/create-genre
Content-Type: application/json

{
  "name": "Reagge"
}


###
POST http://localhost:3000/artist/create-artist
Content-Type: application/json

{
  "name": "Pumapjl",
  "biography": "Pumapjl é um rapper carioca nascido em 1999, conhecido por suas rimas cruas e estilo boom bap. Iniciou a carreira em 2017 e ganhou destaque com o EP 'Naturalidade'. Integra o duo Febre90’s e o coletivo Covil da Bruxa.",
  "genreId": "cmd7lk7c300001d0w4k6tzl5i"
}


###
POST http://localhost:3000/album/create-album
Content-Type: application/json

{
  "name": "Autodominio",
  "artistId": "cmd7muii800015c0vsy9d1d71",
  "genreId": "cmd7lk7c300001d0w4k6tzl5i"

}


###

POST http://localhost:3000/track/create-track
Content-Type: application/json

{
  "name": "Reduto de Malandro",
  "artistId": "cmd7muii800015c0vsy9d1d71",
  "albumId": "cmd7naevk0001zp0vgjo97q7d",
  "genreId": "cmd7lk7c300001d0w4k6tzl5i",
  "duration": 240,
  "isPublic" : true
}


###
GET http://localhost:3000/track/all-tracks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbWVsOHl1M2MwMDA4NjVlY3UxbW4ydGV2IiwidXNlcm5hbWUiOiJkaWVnb3NvdTQiLCJpYXQiOjE3NTU3ODUzMTcsImV4cCI6MTc1NTc4NjIxN30.gUJVIAyGupm_YfL7Tnk66X5iZIlsOZ2MmAnJQp8xT7Q
